modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="masucraftfixes"
version="${file.jarVersion}"
displayName="MasuCraft Fixes"
authors="Masuary"
description='''
Server-side fixes for Vault Hunters: LuckPerms player limit bypass, flight prevention in vaults, and anti-AFK fixes.
'''

[[dependencies.masucraftfixes]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.masucraftfixes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
