modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="masucraftfixes"
version="${file.jarVersion}"
displayName="MasuCraft Fixes"
authors="Masuary"
description='''
Server-side fixes for Vault Hunters, including legacy Vault data compatibility,
Orechid Ignem Nether-biome support, Pickarang item tag filtering,
LuckPerms player limit bypass, and flight prevention in vaults.
'''

[[dependencies.masucraftfixes]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.masucraftfixes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.masucraftfixes]]
    modId="botania"
    mandatory=false
    versionRange="[1.18.2-435]"
    ordering="AFTER"
    side="SERVER"
